# variables:
jobs:
- job: 'Publish'

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - script: dotnet pack --output $(Build.ArtifactStagingDirectory)
    displayName: 'Pack'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish'

- job: 'Test'

  dependsOn:
    - 'Publish'

  strategy:
    matrix:
      Linux:
        os.vmImage: 'ubuntu-16.04'
      macOS:
        os.vmImage: 'macOS-10.13'
      Windows:
        os.vmImage: 'vs2017-win2016'

  pool:
    vmImage: '$(os.vmImage)'

  steps:
    - task: DotNetCoreCLI@2
      displayName: 'Test'
      inputs:
        projects: '**/*.Test/*.csproj'
        command: test
